### PR TITLE
Ensure apply runs on retry and on drift

### PR DESCRIPTION
**Pull request by cezarsa**
Fixes https://github.com/appvia/terranetes-controller/issues/1295

Besides setting the drift and retry annotations on apply Jobs, this PR also ensures an apply Job runs if the drift ensure func marked the resource as OutOfSync.

### CODE REVIEW

**Comment by cezarsa** [comment]
Actually, this PR might not be completely right yet. I'll run some additional tests but there are some weird interactions between drift detection and Configurations requiring manual apply approval. I'll convert this to a draft for now.

**Review by gambol99 — APPROVED** [review]
LGTM .. thank you @cezarsa!

**Comment by gambol99** [comment]
hi @cezarsa … is this one good to go? … or still a draft

**Comment by cezarsa** [comment]
Hey @gambol99 sorry for taking so long, I think this is fine to merge and from what I tested it will fix the linked issue.

Earlier I got confused because I was testing this alongside disabling enableAutoApproval, and that caused different problems which I'll describe in a new issue report.

**Comment by cezarsa** [comment]
This is no longer needed since https://github.com/appvia/terranetes-controller/pull/1367 has been merged.

**Pull request closed without merging**
